// Permission constants
export const PERMISSIONS = {
  // Import permissions
  IMPORT_CREATE: 'IMPORT_CREATE',
  IMPORT_EDIT: 'IMPORT_EDIT',
  IMPORT_DELETE: 'IMPORT_DELETE',
  IMPORT_APPROVE: 'IMPORT_APPROVE',
  IMPORT_REJECT: 'IMPORT_REJECT',
  IMPORT_CANCEL: 'IMPORT_CANCEL',
  IMPORT_CONFIRM: 'IMPORT_CONFIRM',
  IMPORT_VIEW: 'IMPORT_VIEW',
  
  // Export permissions
  EXPORT_CREATE: 'EXPORT_CREATE',
  EXPORT_EDIT: 'EXPORT_EDIT',
  EXPORT_DELETE: 'EXPORT_DELETE',
  EXPORT_APPROVE: 'EXPORT_APPROVE',
  EXPORT_REJECT: 'EXPORT_REJECT',
  EXPORT_CANCEL: 'EXPORT_CANCEL',
  EXPORT_CONFIRM: 'EXPORT_CONFIRM',
  EXPORT_VIEW: 'EXPORT_VIEW',
  
  // Inventory check permissions
  INVENTORY_CHECK_CREATE: 'INVENTORY_CHECK_CREATE',
  INVENTORY_CHECK_EDIT: 'INVENTORY_CHECK_EDIT',
  INVENTORY_CHECK_DELETE: 'INVENTORY_CHECK_DELETE',
  INVENTORY_CHECK_APPROVE: 'INVENTORY_CHECK_APPROVE',
  INVENTORY_CHECK_CONFIRM: 'INVENTORY_CHECK_CONFIRM',
  INVENTORY_CHECK_VIEW: 'INVENTORY_CHECK_VIEW',
  
  // Product permissions
  PRODUCT_VIEW: 'PRODUCT_VIEW',
  PRODUCT_CREATE: 'PRODUCT_CREATE',
  PRODUCT_EDIT: 'PRODUCT_EDIT',
  PRODUCT_DELETE: 'PRODUCT_DELETE',
  
  // Category permissions
  CATEGORY_VIEW: 'CATEGORY_VIEW',
  CATEGORY_CREATE: 'CATEGORY_CREATE',
  CATEGORY_EDIT: 'CATEGORY_EDIT',
  CATEGORY_DELETE: 'CATEGORY_DELETE',
  
  // Supplier permissions
  SUPPLIER_VIEW: 'SUPPLIER_VIEW',
  SUPPLIER_CREATE: 'SUPPLIER_CREATE',
  SUPPLIER_EDIT: 'SUPPLIER_EDIT',
  SUPPLIER_DELETE: 'SUPPLIER_DELETE',
  
  // Customer permissions
  CUSTOMER_VIEW: 'CUSTOMER_VIEW',
  CUSTOMER_CREATE: 'CUSTOMER_CREATE',
  CUSTOMER_EDIT: 'CUSTOMER_EDIT',
  CUSTOMER_DELETE: 'CUSTOMER_DELETE',
  
  // Store permissions
  STORE_VIEW: 'STORE_VIEW',
  STORE_CREATE: 'STORE_CREATE',
  STORE_EDIT: 'STORE_EDIT',
  STORE_DELETE: 'STORE_DELETE',
  
  // Unit permissions
  UNIT_VIEW: 'UNIT_VIEW',
  UNIT_CREATE: 'UNIT_CREATE',
  UNIT_EDIT: 'UNIT_EDIT',
  UNIT_DELETE: 'UNIT_DELETE',
  
  // Report permissions
  REPORT_VIEW: 'REPORT_VIEW',
  REPORT_EXPORT: 'REPORT_EXPORT',
  
  // Member permissions
  MEMBER_VIEW: 'MEMBER_VIEW',
  MEMBER_CREATE: 'MEMBER_CREATE',
  MEMBER_EDIT: 'MEMBER_EDIT',
  MEMBER_DELETE: 'MEMBER_DELETE',
  
  // Role permissions
  ROLE_VIEW: 'ROLE_VIEW',
  ROLE_CREATE: 'ROLE_CREATE',
  ROLE_EDIT: 'ROLE_EDIT',
  ROLE_DELETE: 'ROLE_DELETE',
  
  // Permission management
  PERMISSION_VIEW: 'PERMISSION_VIEW',
  PERMISSION_CREATE: 'PERMISSION_CREATE',
  PERMISSION_EDIT: 'PERMISSION_EDIT',
  PERMISSION_DELETE: 'PERMISSION_DELETE',
  
  // Activity log permissions
  ACTIVITY_LOG_VIEW: 'ACTIVITY_LOG_VIEW',
  ACTIVITY_LOG_DELETE: 'ACTIVITY_LOG_DELETE',
} as const;

// Role-based permission mapping
const ROLE_PERMISSIONS: Record<string, string[]> = {
  // Admin có tất cả quyền
  ADMIN: Object.values(PERMISSIONS),
  
  // Manager có quyền quản lý và duyệt
  MANAGER: [
    // Import/Export
    PERMISSIONS.IMPORT_CREATE,
    PERMISSIONS.IMPORT_EDIT,
    PERMISSIONS.IMPORT_APPROVE,
    PERMISSIONS.IMPORT_REJECT,
    PERMISSIONS.IMPORT_VIEW,
    PERMISSIONS.EXPORT_CREATE,
    PERMISSIONS.EXPORT_EDIT,
    PERMISSIONS.EXPORT_APPROVE,
    PERMISSIONS.EXPORT_REJECT,
    PERMISSIONS.EXPORT_VIEW,
    // Inventory
    PERMISSIONS.INVENTORY_CHECK_CREATE,
    PERMISSIONS.INVENTORY_CHECK_EDIT,
    PERMISSIONS.INVENTORY_CHECK_APPROVE,
    PERMISSIONS.INVENTORY_CHECK_VIEW,
    // Products & Categories
    PERMISSIONS.PRODUCT_VIEW,
    PERMISSIONS.PRODUCT_CREATE,
    PERMISSIONS.PRODUCT_EDIT,
    PERMISSIONS.CATEGORY_VIEW,
    PERMISSIONS.CATEGORY_CREATE,
    PERMISSIONS.CATEGORY_EDIT,
    PERMISSIONS.SUPPLIER_VIEW,
    PERMISSIONS.SUPPLIER_CREATE,
    PERMISSIONS.SUPPLIER_EDIT,
    PERMISSIONS.CUSTOMER_VIEW,
    PERMISSIONS.CUSTOMER_CREATE,
    PERMISSIONS.CUSTOMER_EDIT,
    PERMISSIONS.STORE_VIEW,
    PERMISSIONS.STORE_CREATE,
    PERMISSIONS.STORE_EDIT,
    PERMISSIONS.UNIT_VIEW,
    PERMISSIONS.UNIT_CREATE,
    PERMISSIONS.UNIT_EDIT,
    // Reports
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_EXPORT,
  ],
  
  // Staff chỉ có quyền tạo và xem
  STAFF: [
    PERMISSIONS.IMPORT_CREATE,
    PERMISSIONS.IMPORT_VIEW,
    PERMISSIONS.EXPORT_CREATE,
    PERMISSIONS.EXPORT_VIEW,
    PERMISSIONS.INVENTORY_CHECK_CREATE,
    PERMISSIONS.INVENTORY_CHECK_VIEW,
    PERMISSIONS.PRODUCT_VIEW,
    PERMISSIONS.CATEGORY_VIEW,
    PERMISSIONS.SUPPLIER_VIEW,
    PERMISSIONS.CUSTOMER_VIEW,
    PERMISSIONS.STORE_VIEW,
    PERMISSIONS.UNIT_VIEW,
  ],
  
  // User chỉ có quyền xem
  USER: [
    PERMISSIONS.IMPORT_VIEW,
    PERMISSIONS.EXPORT_VIEW,
    PERMISSIONS.INVENTORY_CHECK_VIEW,
    PERMISSIONS.PRODUCT_VIEW,
    PERMISSIONS.CATEGORY_VIEW,
    PERMISSIONS.SUPPLIER_VIEW,
    PERMISSIONS.CUSTOMER_VIEW,
    PERMISSIONS.STORE_VIEW,
    PERMISSIONS.UNIT_VIEW,
  ],
};

/**
 * Kiểm tra xem user có quyền thực hiện một hành động không
 */
export function hasPermission(userRoles: string[], permission: string): boolean {
  if (!userRoles || userRoles.length === 0) return false;
  
  // Kiểm tra từng role của user
  for (const role of userRoles) {
    const roleUpper = role.toUpperCase();
    const permissions = ROLE_PERMISSIONS[roleUpper] || [];
    
    // Nếu role có quyền này hoặc là ADMIN
    if (permissions.includes(permission) || roleUpper === 'ADMIN') {
      return true;
    }
  }
  
  return false;
}

/**
 * Kiểm tra xem user có một trong các roles được chỉ định không
 */
export function hasRole(userRoles: string[], allowedRoles: string[]): boolean {
  if (!userRoles || userRoles.length === 0) return false;
  
  const userRolesUpper = userRoles.map(r => r.toUpperCase());
  const allowedRolesUpper = allowedRoles.map(r => r.toUpperCase());
  
  return userRolesUpper.some(role => allowedRolesUpper.includes(role));
}

